### ISSUE TITLE
GulpIO data creation error

### ISSUE THREAD

**Issue by in-skyadav** [TwentyBN/GulpIO-benchmarks#2]
steps taken before running the data preparation command :
1. synched "https://github.com/TwentyBN/GulpIO".
2. Downloaded the "https://20bn.com/datasets/jester/v1#download" data.
3. setup the GulpIO-master project.
4. run the below command 
gulp_20bn_csv_jpeg --num_workers=8 csv_files/jester-v1-train.csv /hdd/20bn-datasets/20bn-jester-v1 /hdd/20bn-datasets/20bn-jester-v1-gulpio/train/
to create training data, getting following error.

Failed to write video with id: 54737; no frames
Failed to write video with id: 145747; no frames
Failed to write video with id: 66575; no frames
Failed to write video with id: 18739; no frames
Also, gulp file is created with size of 0KB. 

please help me how to prepare data.

**Comment by raghavgoyal14** [comment]
Hi,

Thanks for trying out the code.
The script you are trying to run is `gulp_20bn_csv_jpeg` which expects correct path to:
- `jpeg_directory`: where you stored the dataset after downloading from 20bn.com. I used the directory `/hdd/20bn-datasets/20bn-jester-v1`. Please check whether it's the same in your case, because the loader is unable to locate the jpeg files.

Full doc: https://github.com/TwentyBN/GulpIO/blob/master/src/main/scripts/gulp_20bn_csv_jpeg

**Comment by in-skyadav** [comment]
> Hi,
> 
> Thanks for trying out the code.
> The script you are trying to run is `gulp_20bn_csv_jpeg` which expects correct path to:
> 
> * `jpeg_directory`: where you stored the dataset after downloading from 20bn.com. I used the directory `/hdd/20bn-datasets/20bn-jester-v1`. Please check whether it's the same in your case, because the loader is unable to locate the jpeg files.
> 
> Full doc: https://github.com/TwentyBN/GulpIO/blob/master/src/main/scripts/gulp_20bn_csv_jpeg

Here the full command which i run : 
gulp_20bn_csv_jpeg --num_workers=8 /home/user/Sandeep/GulpIO-master/csv_files/jester-v1-train.csv /home/user/Sandeep/GulpIO-master/jester_data/20bn-jester-v1 /home/user/Sandeep/GulpIO-master/gulp_data/train

/home/user/Sandeep/GulpIO-master/csv_files/jester-v1-train.csv  : path of CSV files. 
/home/user/Sandeep/GulpIO-master/jester_data/20bn-jester-v1 : path of data downloaded form 20bn website. 
/home/user/Sandeep/GulpIO-master/gulp_data/train : path of output file.

but the file at path "/home/user/Sandeep/GulpIO-master/jester_data/20bn-jester-v1" is not jpeg, this folder contains the list of downloaded file...(20bn-jester-v1-00,20bn-jester-v1-01,20bn-jester-v1-02,20bn-jester-v1-03... 20bn-jester-v1-22)

**Comment by raghavgoyal14** [comment]
Hi,

Can you extract the files and try again?

![image](https://user-images.githubusercontent.com/2176778/46467987-85b21b80-c7cf-11e8-83b0-51b499ee7881.png)

ref: https://20bn.com/datasets/jester/v1#download

**Comment by in-skyadav** [comment]
> Hi,
> 
> Can you extract the files and try again?
> 
> ![image](https://user-images.githubusercontent.com/2176778/46467987-85b21b80-c7cf-11e8-83b0-51b499ee7881.png)
> 
> ref: https://20bn.com/datasets/jester/v1#download

yes, by doing this I am able to create the data successfully.
thank you

**Comment by in-skyadav** [comment]
Error is resolved.
