### ISSUE TITLE
When trying to create a model for 2 class i am getting following error

### ISSUE THREAD

**Issue by in-skyadav** [TwentyBN/GulpIO-benchmarks#3]
I used the same model to train 2 class, modified the data as well as config file accordingly.
I got following error when run the python train_gulp.py

below are the log traces : 

=> active GPUs: 0
=> Output folder for this run -- jester_conv_example
 > Using 10 processes for data loader.
 > Training is getting started...
 > Training takes 200 epochs.
 > Current LR : 0.001
Traceback (most recent call last):
  File "train_gulp.py", line 365, in <module>
    main()
  File "train_gulp.py", line 185, in main
    train_loader, model, criterion, optimizer, epoch)
  File "train_gulp.py", line 241, in train
    prec1, prec5 = accuracy(output.data, target, topk=(1, 5))
  File "train_gulp.py", line 353, in accuracy
    _, pred = output.cpu().topk(maxk, 1, True, True)
RuntimeError: invalid argument 2: k not in range for dimension at /pytorch/torch/lib/TH/generic/THTensorMath.c:2750

**Comment by raghavgoyal14** [comment]
Since you are using the code to train a model with 2 classes, I believe you have to omit `5` in 
```
File "train_gulp.py", line 241, in train
prec1, prec5 = accuracy(output.data, target, topk=(1, 5))
```

Can you please try and see whether it works?

**Comment by in-skyadav** [comment]
> Since you are using the code to train a model with 2 classes, I believe you have to omit `5` in
> 
> ```
> File "train_gulp.py", line 241, in train
> prec1, prec5 = accuracy(output.data, target, topk=(1, 5))
> ```
> Can you please try and see whether it works?

by setting maxk value to 2 in accuracy function I am able to able to start the training and model is generated too "checkpoint.pth.tar" and "model_best.pth.tar" file.

def accuracy(output, target, topk=(1,)):
    """Computes the precision@k for the specified values of k"""
    maxk = max(topk)
    maxk = 2
...
}

One more query : how to use this model in Android or any desktop based application ?

**Comment by raghavgoyal14** [comment]
Unfortunately, this repository is only concerned with setting up training/validation ML pipeline and doesn't support deployment.

**Comment by in-skyadav** [comment]
able to build model successfully so closing.
