### ISSUE TITLE
porting the model for Android devices.

### ISSUE THREAD

**Issue by in-skyadav** [TwentyBN/GulpIO-benchmarks#5]
I am trying to use this model on Android device. I have done training for only two gesture for testing purpose.
I have few queries :
1. Is it possible to use this model completely on Android mobile device.
2. If yes, then what would be the latency to recognize a particular gesture can I use it as Real-time ?

**Comment by raghavgoyal14** [comment]
Unfortunately I don't have sufficient expertise in the area. Please check ways to port PyTorch models to Android.
