### ISSUE TITLE
step_size in VideoFolder class

### ISSUE THREAD

**Issue by rhsieh91** [TwentyBN/GulpIO-benchmarks#6]
In the VideoFolder class, what does step_size control?

**Comment by raghavgoyal14** [comment]
ref: https://github.com/TwentyBN/GulpIO-benchmarks/blob/master/data_loader_gulpio.py#L55

`step_size` controls the interval with which frames are sampled from the original frames.
1 => sample every frame (maintains the original frame rate)
2 => sample every 2nd frame (halves the original frame rate)
and so on ...
