### ISSUE TITLE
Random offset when self.is_val=False

### ISSUE THREAD

**Issue by rhsieh91** [TwentyBN/GulpIO-benchmarks#7]
In the VideoFolder class, what is the rationale for adding a random offset during clip generation only when self.is_val=False?

**Comment by raghavgoyal14** [comment]
The idea here is that if you'd like to subsample a smaller clip from the video during training phase, then this random offset will fetch you a random clip for each iteration of the training phase. Kind of like data augmentation in temporal domain.
